name = "prismatyx/delta"
version = "1.0.4"
description = "Deterministic physics library for Roblox"
authors = ["prismatyx"]
repository = "https://github.com/prisma-dev/delta"
license = "MIT"
includes = ["out/**/*.luau", "out/**/*.lua","pesde.toml"]

[target]
environment = "roblox"
lib = "out/init.luau"
build_files = ["out"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
