[package]
name = "prisma-dev/delta"
description = "Deterministic physics library for Roblox"
version = "1.1.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["delta","delta/include/**","delta/source/**","delta/tests/**","delta/source/util/**","delta/source/util/helper/**","delta/source/util/math/**","delta/include/node_modules/**","delta/include/node_modules/***","default.project.json", "wally.toml"]